"""Read-only data access for the dashboard. The only module here that touches a session."""

from dashboard.services.dashboard_service import (
    DatabaseUnavailable,
    describe_database,
    load_alert_detail,
    load_alerts,
    load_component_activity,
    load_evidence,
    load_filter_options,
    load_latest_readings,
    load_machine_detail,
    load_machines,
    load_notifications,
    load_overview,
    load_parameter_catalogue,
    load_prediction_detail,
    load_predictions,
    load_recommendation_detail,
    load_recommendations,
    load_traceability,
    load_trend,
    resolve_database_path,
)

__all__ = [
    "DatabaseUnavailable",
    "describe_database",
    "load_alert_detail",
    "load_alerts",
    "load_component_activity",
    "load_evidence",
    "load_filter_options",
    "load_latest_readings",
    "load_machine_detail",
    "load_machines",
    "load_notifications",
    "load_overview",
    "load_parameter_catalogue",
    "load_prediction_detail",
    "load_predictions",
    "load_recommendation_detail",
    "load_recommendations",
    "load_traceability",
    "load_trend",
    "resolve_database_path",
]
