"""Re-exports all 65 controlled-vocabulary enum classes (§40.7).

65 vocabularies, 65 classes, 100 bound columns. In the database each vocabulary
is a TEXT column plus a named ``CHECK (column IN (...))`` constraint -- there is
no type object, because SQLite has none. That makes these classes the only place
a vocabulary is named as a single thing, and what keeps 100 per-column
constraints agreeing with one another (§40.1).
"""

from models.enums.master import (
    AccessRestriction,
    AreaType,
    BusinessRuleCategory,
    BusinessRuleValueType,
    CapabilityType,
    CriticalityLevel,
    CustomerPriorityTier,
    DegradationDirection,
    DepartmentFunction,
    DriftDirection,
    EmploymentType,
    EquipmentClass,
    FailureDomain,
    IntervalBasis,
    InventoryItemType,
    InventoryLocationType,
    LineType,
    MachineLifecycleStatus,
    MaintenanceSpecialization,
    MaintenanceType,
    MeasurementDomain,
    ParameterDataType,
    QualityCriticality,
    RelativeFrequency,
    RoleCategory,
    ShiftType,
    SkillLevel,
    SupplierType,
    ThresholdSensitivity,
    UnitOfMeasure,
)
from models.enums.operational import (
    AlertResolutionType,
    AlertStatus,
    AlertSuppressionReason,
    CycleOutcome,
    DeliveryChannel,
    DeliveryFailureReason,
    DeliveryStatus,
    EscalationDecision,
    EventCategory,
    EventType,
    InspectionDisposition,
    InspectionType,
    InventoryMovementType,
    MachineOperationalState,
    MaintenanceActivityType,
    MaintenanceWorkStatus,
    MaintenanceWorkType,
    NotificationSuppressionReason,
    NotificationType,
    ReadingQualityFlag,
    RecommendationActionType,
    RejectionReason,
    RootCauseConfidence,
    RunPauseReason,
    RunPriority,
    RunStatus,
    ScrapReason,
    SnapshotInsufficiencyReason,
    SnapshotScope,
    StateTransitionReason,
    ThresholdDirection,
)
from models.enums.system import (
    AuditActionType,
    AuditOutcome,
    ComponentHealthStatus,
    PlatformComponent,
)

__all__ = [
    # master - 30
    "AccessRestriction",
    "AreaType",
    "BusinessRuleCategory",
    "BusinessRuleValueType",
    "CapabilityType",
    "CriticalityLevel",
    "CustomerPriorityTier",
    "DegradationDirection",
    "DepartmentFunction",
    "DriftDirection",
    "EmploymentType",
    "EquipmentClass",
    "FailureDomain",
    "IntervalBasis",
    "InventoryItemType",
    "InventoryLocationType",
    "LineType",
    "MachineLifecycleStatus",
    "MaintenanceSpecialization",
    "MaintenanceType",
    "MeasurementDomain",
    "ParameterDataType",
    "QualityCriticality",
    "RelativeFrequency",
    "RoleCategory",
    "ShiftType",
    "SkillLevel",
    "SupplierType",
    "ThresholdSensitivity",
    "UnitOfMeasure",
    # operational - 31
    "AlertResolutionType",
    "AlertStatus",
    "AlertSuppressionReason",
    "CycleOutcome",
    "DeliveryChannel",
    "DeliveryFailureReason",
    "DeliveryStatus",
    "EscalationDecision",
    "EventCategory",
    "EventType",
    "InspectionDisposition",
    "InspectionType",
    "InventoryMovementType",
    "MachineOperationalState",
    "MaintenanceActivityType",
    "MaintenanceWorkStatus",
    "MaintenanceWorkType",
    "NotificationSuppressionReason",
    "NotificationType",
    "ReadingQualityFlag",
    "RecommendationActionType",
    "RejectionReason",
    "RootCauseConfidence",
    "RunPauseReason",
    "RunPriority",
    "RunStatus",
    "ScrapReason",
    "SnapshotInsufficiencyReason",
    "SnapshotScope",
    "StateTransitionReason",
    "ThresholdDirection",
    # system - 4
    "AuditActionType",
    "AuditOutcome",
    "ComponentHealthStatus",
    "PlatformComponent",
]
