"""The AI Recommendations page: the Decision Agent's output, whole and unedited.

The dashboard is the surface with room, so the recommendation is shown in full here --
no truncation, no summary, no rewrite. The WhatsApp message keeps its own excerpt for
reading on a phone. Both come from the same persisted row and the same formatting
authority, which is why they cannot disagree about a number.
"""

from __future__ import annotations

from typing import Any

import pandas as pd
import streamlit as st

from dashboard.components import (
    empty,
    kpi_row,
    masthead,
    section,
    severity_badge,
    status_badge,
    traceability_chain,
)
from dashboard.components.layout import card, field_grid, prose
from dashboard.services import (
    load_evidence,
    load_recommendation_detail,
    load_recommendations,
    load_traceability,
)
from dashboard.styles.theme import severity_colour
from dashboard.views import (
    apply_filters,
    close_detail,
    navigate,
    open_detail,
    search,
    selection,
)


def render(db_path: str, filters: dict[str, Any], database: dict[str, Any]) -> None:
    masthead("AI Recommendations",
             "Diagnosis, action, ownership and timing, as generated by the Decision Agent")

    recommendations = load_recommendations(db_path)
    if not recommendations:
        empty("No recommendations available.",
              "A recommendation exists only where the escalation gate escalated a "
              "prediction. Suppressed situations are recorded on the Alerts page.")
        return

    chosen = selection("selected_recommendation")
    if chosen and any(r["code"] == chosen for r in recommendations):
        _detail(db_path, chosen)
        return

    _list(recommendations, filters)


# ------------------------------------------------------------------------ list


def _list(recommendations: list[dict[str, Any]], filters: dict[str, Any]) -> None:
    rows = apply_filters(recommendations, filters, {
        "machine": "machine_code", "severity": "severity"})
    wanted = filters.get("category")
    if wanted and wanted != "All":
        rows = [r for r in rows if r["category"] == wanted]

    term = st.text_input("Search recommendations",
                         placeholder="recommendation code, machine or failure",
                         key="rec_search", label_visibility="collapsed")
    rows = search(rows, term, ["code", "machine_code", "machine_name", "category",
                              "prediction_code"])

    complete = [r for r in rows if r["contract_complete"]]
    kpi_row([
        {"label": "Shown", "value": len(rows),
         "note": "of %d recommendations" % len(recommendations), "tone": "info"},
        {"label": "Contract Complete", "value": len(complete),
         "note": "all five reasoning elements produced",
         "tone": "healthy" if len(complete) == len(rows) else "warning"},
        {"label": "Total Downtime at Risk",
         "value": "%s min" % "{:,}".format(
             sum(r["downtime_minutes"] or 0 for r in rows)),
         "tone": "warning"},
    ])

    section("Recommendation List")
    if not rows:
        empty("No recommendations match the current filters.")
        return

    for recommendation in rows:
        body, action = st.columns([6, 1])
        with body:
            card(
                '<div style="display:flex;align-items:center;gap:0.55rem;'
                'flex-wrap:wrap"><span class="ff-code" style="font-weight:660">%s</span>'
                '%s</div>'
                '<div style="margin-top:0.34rem;font-size:0.9rem">%s &middot; %s</div>'
                '<div class="ff-muted" style="margin-top:0.26rem;font-size:0.82rem">'
                '%s &middot; %s horizon &middot; downtime %s &middot; act by %s</div>'
                % (recommendation["code"], severity_badge(recommendation["severity"]),
                   recommendation["machine_code"], recommendation["category"],
                   recommendation["probability_display"],
                   recommendation["horizon_display"],
                   recommendation["downtime_display"],
                   recommendation["deadline"]["display"]),
                accent=severity_colour(recommendation["severity"].get("colour"),
                                       recommendation["severity"].get("rank")))
        with action:
            st.write("")
            if st.button("Open", key="rc_%s" % recommendation["code"],
                         width="stretch"):
                open_detail("selected_recommendation", recommendation["code"])
        st.write("")


# ---------------------------------------------------------------------- detail


def _detail(db_path: str, code: str) -> None:
    detail = load_recommendation_detail(db_path, code)
    if detail is None:
        empty("Recommendation %s was not found." % code)
        return
    fields = detail["fields"]

    back, _ = st.columns([1, 5])
    with back:
        if st.button("Back to list", width="stretch", key="rc_back",
                     icon=":material/arrow_back:"):
            close_detail("selected_recommendation")

    card(
        '<div style="display:flex;align-items:center;gap:0.6rem;flex-wrap:wrap">'
        '<span class="ff-code" style="font-weight:680;font-size:1.1rem">%s</span>%s%s</div>'
        '<div class="ff-muted" style="margin-top:0.34rem;font-size:0.86rem">'
        '%s &middot; generated %s by %s</div>'
        % (detail["code"], severity_badge(detail["severity"]),
           status_badge(detail["notification_status"], "delivery"),
           fields["machine"]["display"], detail["generated_at"]["display"],
           detail["llm_model"]),
        accent=severity_colour(detail["severity"].get("colour"),
                               detail["severity"].get("rank")))

    # Two columns: what the platform concluded, beside who has to act on it. Both fit in a
    # screen height together, and reading them side by side is how an operator actually uses
    # them -- "how bad, by when" and "whose job" are one decision.
    diagnosis, response = st.columns([3, 2], gap="medium")

    with diagnosis:
        section("Diagnosis")
        field_grid([
            {"label": fields["machine"]["label"],
             "value": fields["machine"]["display"]},
            {"label": fields["failure_type"]["label"],
             "value": fields["failure_type"]["display"]},
            {"label": fields["severity"]["label"],
             "html": severity_badge(detail["severity"])},
            {"label": fields["failure_probability"]["label"],
             "value": fields["failure_probability"]["display"],
             "raw": fields["failure_probability"]["value"]},
            {"label": fields["prediction_horizon"]["label"],
             "value": fields["prediction_horizon"]["display"],
             "raw": "%s hours" % fields["prediction_horizon"]["value"]},
            {"label": fields["estimated_downtime"]["label"],
             "value": fields["estimated_downtime"]["display"],
             "raw": fields["estimated_downtime"]["value"]},
            {"label": fields["deadline"]["label"],
             "value": fields["deadline"]["display"],
             "raw": fields["deadline"]["value"]},
        ])

    with response:
        section("Assigned Response")
        field_grid([
            {"label": "Engineer",
             "value": detail["engineer_name"] or fields["engineer"]["display"],
             "raw": detail["engineer"]},
            {"label": "Team", "value": detail["team_name"] or fields["team"]["display"],
             "raw": detail["team"]},
            {"label": "Root Cause Confidence", "value": detail["confidence"]},
            {"label": "Contract Complete",
             "value": "yes" if detail["contract_complete"] else "no"},
            {"label": fields["notification_status"]["label"],
             "html": status_badge(detail["notification_status"], "delivery")
             if detail["notification_status"] else None,
             "value": None if detail["notification_status"] else "not dispatched"},
        ])

    _reasoning(fields)
    _impact(detail)
    _evidence(db_path, code, fields)
    _chain(db_path, code)


# -------------------------------------------------------------------- reasoning


def _reasoning(fields: dict[str, Any]) -> None:
    recommendation = fields["recommendation"]

    section("Recommended Action")
    prose(recommendation["display"])
    st.caption("Shown in full, exactly as generated. %d characters."
               % len(recommendation["display"] or ""))

    section("Recovery Plan")
    prose(recommendation.get("recovery_plan_display")
          or recommendation.get("recovery_plan"))

    section("Reasoning")
    prose(recommendation.get("reasoning_narrative_display")
          or recommendation.get("reasoning_narrative"))

    with st.expander("Stored text at full recorded precision"):
        st.caption(
            "The database keeps the Decision Agent's text verbatim. What is displayed "
            "above brings its measurements to engineering precision; nothing else "
            "differs, and the stored value is never rewritten.")
        st.text_area("Recommended action as stored", recommendation["value"],
                     height=180, disabled=True, key="rc_raw_action")


def _impact(detail: dict[str, Any]) -> None:
    impact = detail.get("business_impact") or {}
    if not impact:
        return
    section("Business Impact")
    flat = {k: v for k, v in impact.items() if not isinstance(v, (dict, list))}
    if flat:
        field_grid([
            {"label": key.replace("_", " ").title(), "value": value}
            for key, value in sorted(flat.items())
        ])
    nested = {k: v for k, v in impact.items() if isinstance(v, (dict, list))}
    if nested:
        with st.expander("Full business impact document"):
            st.json(impact, expanded=False)


# --------------------------------------------------------------------- evidence


def _evidence(db_path: str, code: str, fields: dict[str, Any]) -> None:
    section("Supporting Evidence")
    evidence = load_evidence(db_path, code)
    if evidence is None:
        empty("No evidence document is attached to this recommendation.")
        return

    kpi_row([
        {"label": "Events", "value": "{:,}".format(evidence["event_count"]),
         "tone": "info"},
        {"label": "Parameters", "value": evidence["parameter_count"],
         "tone": "neutral"},
        {"label": "Corroborating Sources", "value": evidence["corroboration_count"],
         "note": "two independent paths permit high confidence",
         "tone": "healthy" if evidence["corroboration_count"] >= 2 else "warning"},
    ])

    trend = fields.get("prediction_trend", {})
    if trend.get("display") and trend["display"] != "no trend recorded":
        st.write("")
        st.markdown("**%s**" % trend["label"])
        prose(trend["display"])

    if evidence["corroboration"]:
        with st.expander("Corroborating findings (%d)"
                         % evidence["corroboration_count"]):
            for entry in evidence["corroboration"]:
                st.markdown("- **%s** — %s" % (entry.get("source", "unknown"),
                                               entry.get("finding", "")))

    if evidence["readings"]:
        with st.expander("Parameter readings (%d)" % len(evidence["readings"])):
            st.dataframe(pd.DataFrame(evidence["readings"]),
                         width="stretch", hide_index=True)

    if st.button("Open full evidence view", key="rc_ev",
                 icon=":material/account_tree:"):
        navigate("Evidence", selected_recommendation=code)


def _chain(db_path: str, code: str) -> None:
    section("Traceability")
    chain = next((c for c in load_traceability(db_path)
                  if c["recommendation"] == code), None)
    if chain is None:
        empty("No chain could be resolved for this recommendation.")
        return
    traceability_chain(chain)
    st.caption("Every link is a foreign key on the row, not a match on codes or times. "
               "An absent link means the relationship does not exist in the database.")

    # The chain is only worth showing if a reader can follow it. A button appears for each
    # link that actually resolves, so nothing on screen looks clickable when it is not.
    left, middle, right, _ = st.columns([1, 1, 1, 2])
    with left:
        if chain.get("prediction") and st.button(
                "Open prediction", width="stretch", key="rc_open_pred",
                icon=":material/insights:"):
            navigate("Predictions", selected_prediction=chain["prediction"])
    with middle:
        if chain.get("alert") and st.button(
                "Open alert", width="stretch", key="rc_open_alert",
                icon=":material/notification_important:"):
            navigate("Alerts", selected_alert=chain["alert"])
    with right:
        if chain.get("notifications") and st.button(
                "Open notifications", width="stretch", key="rc_open_ntf",
                icon=":material/send:"):
            navigate("Notifications",
                     selected_notification=chain["notifications"][0])
